### ISSUE TITLE
Sorted

### ISSUE THREAD

**Issue by thiago-molive** [Nucito/CaptchaSolver#2]
Boa mano obrigado pela contribuição. Deixa eu te falar eu tava testando e percebi que ele n tá ordenando de acordo com o eixo x da imagem e no final ele reconhece todos os números porém na ordem que ele reconheceu nem sempre é a ordem correta.

Eu tentei adicionar um sorted pelo x, mas sem sucesso. Consegue ajudar?

**Comment by Nucito** [comment]
@thiago-molive Opa eu tinha notado esse erro na ultima versão, tente baixar a ultima versão aqui do github😁

**Comment by fguide** [comment]
Utilizando com o mais recente não notei esse problema, mas testei pouco, se perceber algo reporto aqui.

**Comment by Nucito** [comment]
Vou considerar como resolvido, se tiver outro problema pode abrir um issue novo.

**Comment by thiago-molive** [comment]
opa, eu consegui resolver e integrei no projeto do bomb la. dps da uma olhada ficou bem legal.

coloquei a declaração do model pra uma função acima que ai posso chamar junto da instancia e evitar carregar o modelo toda que eu chamar a função pra tentar descobrir o captcha. (agora que to escrevendo aqui percebi q eu devia ter colocado no construtor e evitado ter que chamar a função)

https://github.com/thiago-molive/bombcrypto-bot/tree/main/CaptchaSolver
