### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by panghuahua2017** [Nucito/CaptchaSolver#3]
ERROR: Could not find a version that satisfies the requirement torch>=1.7.0 (from versions: none)
ERROR: No matching distribution found for torch>=1.7.0

Sir ,how can I solve it? I tried to download torch from the official website, but it prompted the version to be unavailable.

**Comment by Nucito** [comment]
@panghuahua2017 Whats is your python version?

**Comment by panghuahua2017** [comment]
@Nucito python-3.10.0-amd64 sir

**Comment by Nucito** [comment]
@panghuahua2017 Unfortunately the torch only supports python versions 3.9.x or below😅

**Comment by Nucito** [comment]
@panghuahua2017 If you want to continue using your version, I recommend that you install version 3.9 in a virtualenv😁

**Comment by panghuahua2017** [comment]
Okay, I will replace the existing python version, thank you.another question, can it be running at the same time with the bot by@mpcabete ?https://github.com/mpcabete/bombcrypto-bot

**Comment by Nucito** [comment]
@mpcabete is using exactly this code, I have contact with him through discord, if you look at the latest version of it you will see that there is the folder of this project inside the code.

**Comment by panghuahua2017** [comment]
@Nucito Are you saying that he has merged your code into it?

**Comment by panghuahua2017** [comment]
I don't understand this much, I confirmed it, he seems to have been updated, thank you so much! ! !

**Comment by Nucito** [comment]
> Are you saying that he has merged your code into it?

Yes 😁

**Comment by Nucito** [comment]
> I don't understand this much, I confirmed it, he seems to have been updated, thank you so much! ! !

Hope you like the code😁

**Comment by panghuahua2017** [comment]
C:\Users\2017\Desktop\CaptchaSolver>python captcha_solver.py

                 from  n    params  module                                  arguments
  0                -1  1      3520  models.common.Focus                     [3, 32, 3]
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]
  2                -1  1     19904  models.common.BottleneckCSP             [64, 64, 1]
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]
  4                -1  1    161152  models.common.BottleneckCSP             [128, 128, 3]
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]
  6                -1  1    641792  models.common.BottleneckCSP             [256, 256, 3]
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]
  8                -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]
  9                -1  1   1248768  models.common.BottleneckCSP             [512, 512, 1, False]
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 12           [-1, 6]  1         0  models.common.Concat                    [1]
 13                -1  1    378624  models.common.BottleneckCSP             [512, 256, 1, False]
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 16           [-1, 4]  1         0  models.common.Concat                    [1]
 17                -1  1     95104  models.common.BottleneckCSP             [256, 128, 1, False]
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
 19          [-1, 14]  1         0  models.common.Concat                    [1]
 20                -1  1    313088  models.common.BottleneckCSP             [256, 256, 1, False]
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]
 22          [-1, 10]  1         0  models.common.Concat                    [1]
 23                -1  1   1248768  models.common.BottleneckCSP             [512, 512, 1, False]
 24      [17, 20, 23]  1     40455  models.yolo.Detect                      [10, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
C:\Users\2017\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ..\aten\src\ATen\native\TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Model Summary: 283 layers, 7279367 parameters, 7279367 gradients, 16.9 GFLOPS

Adding autoShape...
{'Captcha': '861', 'Cods': [{'6': {'x1': 47.03, 'y1': 278.7, 'x2': 159.94, 'y2': 357.61, 'per': 0.91}}, {'1': {'x1': 37.01, 'y1': 366.24, 'x2': 180.87, 'y2': 399.01, 'per': 0.91}}, {'8': {'x1': 47.16, 'y1': 195.8, 'x2': 152.64, 'y2': 263.24, 'per': 0.85}}]}

C:\Users\2017\Desktop\CaptchaSolver>python captcha_solver.py

                 from  n    params  module                                  arguments
  0                -1  1      3520  models.common.Focus                     [3, 32, 3]
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]
  2                -1  1     19904  models.common.BottleneckCSP             [64, 64, 1]
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]
  4                -1  1    161152  models.common.BottleneckCSP             [128, 128, 3]
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]
  6                -1  1    641792  models.common.BottleneckCSP             [256, 256, 3]
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]
  8                -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]
  9                -1  1   1248768  models.common.BottleneckCSP             [512, 512, 1, False]
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 12           [-1, 6]  1         0  models.common.Concat                    [1]
 13                -1  1    378624  models.common.BottleneckCSP             [512, 256, 1, False]
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 16           [-1, 4]  1         0  models.common.Concat                    [1]
 17                -1  1     95104  models.common.BottleneckCSP             [256, 128, 1, False]
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
 19          [-1, 14]  1         0  models.common.Concat                    [1]
 20                -1  1    313088  models.common.BottleneckCSP             [256, 256, 1, False]
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]
 22          [-1, 10]  1         0  models.common.Concat                    [1]
 23                -1  1   1248768  models.common.BottleneckCSP             [512, 512, 1, False]
 24      [17, 20, 23]  1     40455  models.yolo.Detect                      [10, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
C:\Users\2017\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ..\aten\src\ATen\native\TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Model Summary: 283 layers, 7279367 parameters, 7279367 gradients, 16.9 GFLOPS

Adding autoShape...
{'Captcha': '861', 'Cods': [{'6': {'x1': 47.03, 'y1': 278.7, 'x2': 159.94, 'y2': 357.61, 'per': 0.91}}, {'1': {'x1': 37.01, 'y1': 366.24, 'x2': 180.87, 'y2': 399.01, 'per': 0.91}}, {'8': {'x1': 47.16, 'y1': 195.8, 'x2': 152.64, 'y2': 263.24, 'per': 0.85}}]}

C:\Users\2017\Desktop\CaptchaSolver>python -m pip install --upgrade pip
Requirement already satisfied: pip in c:\users\2017\appdata\local\programs\python\python39\lib\site-packages (21.2.4)
Collecting pip
  Downloading pip-21.3.1-py3-none-any.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 42 kB/s
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.4
    Uninstalling pip-21.2.4:
      Successfully uninstalled pip-21.2.4
Successfully installed pip-21.3.1

C:\Users\2017\Desktop\CaptchaSolver>python captcha_solver.py

                 from  n    params  module                                  arguments
  0                -1  1      3520  models.common.Focus                     [3, 32, 3]
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]
  2                -1  1     19904  models.common.BottleneckCSP             [64, 64, 1]
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]
  4                -1  1    161152  models.common.BottleneckCSP             [128, 128, 3]
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]
  6                -1  1    641792  models.common.BottleneckCSP             [256, 256, 3]
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]
  8                -1  1    656896  models.common.SPP                       [512, 512, [5, 9, 13]]
  9                -1  1   1248768  models.common.BottleneckCSP             [512, 512, 1, False]
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 12           [-1, 6]  1         0  models.common.Concat                    [1]
 13                -1  1    378624  models.common.BottleneckCSP             [512, 256, 1, False]
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']
 16           [-1, 4]  1         0  models.common.Concat                    [1]
 17                -1  1     95104  models.common.BottleneckCSP             [256, 128, 1, False]
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]
 19          [-1, 14]  1         0  models.common.Concat                    [1]
 20                -1  1    313088  models.common.BottleneckCSP             [256, 256, 1, False]
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]
 22          [-1, 10]  1         0  models.common.Concat                    [1]
 23                -1  1   1248768  models.common.BottleneckCSP             [512, 512, 1, False]
 24      [17, 20, 23]  1     40455  models.yolo.Detect                      [10, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
C:\Users\2017\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ..\aten\src\ATen\native\TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Model Summary: 283 layers, 7279367 parameters, 7279367 gradients, 16.9 GFLOPS

Adding autoShape...
{'Captcha': '861', 'Cods': [{'6': {'x1': 47.03, 'y1': 278.7, 'x2': 159.94, 'y2': 357.61, 'per': 0.91}}, {'1': {'x1': 37.01, 'y1': 366.24, 'x2': 180.87, 'y2': 399.01, 'per': 0.91}}, {'8': {'x1': 47.16, 'y1': 195.8, 'x2': 152.64, 'y2': 263.24, 'per': 0.85}}]}

I seem to have other problems^ ^

**Comment by panghuahua2017** [comment]
Traceback (most recent call last):
  File "C:\Users\2017\Desktop\bot\index.py", line 696, in <module>
    solveNewCaptcha()
  File "C:\Users\2017\Desktop\bot\index.py", line 692, in solveNewCaptcha
    img = images['nc']
KeyError: 'nc'

When I try to run mpcabete's robot, I get this prompt, can you fix it for me

**Comment by panghuahua2017** [comment]
It seems that the mpcabete's bot has not been completed yet, and it seems to have to wait. Thank you for your patience.

**Comment by Nucito** [comment]
> It seems that the mpcabete's bot has not been completed yet, and it seems to have to wait. Thank you for your patience.

The mpcabete will release a new version soon 😁

**Comment by Nucito** [comment]
> 

The error **UserWarning** is only a warning in this version of pytorch you can supress this with logger 😁
