### ISSUE TITLE
Python downgrade

### ISSUE THREAD

**Issue by VitotEPB** [Nucito/CaptchaSolver#4]
Você pode fazer um tutorial de como regredir o Python 3.1 pra o 3.9.9?

**Comment by Nucito** [comment]
Infelizmente isso ai não vai dar para mim 😁 Esse tipo de coisa você encontra facilmente com uma simples pesquisa no google...

[Link](https://pt.stackoverflow.com/questions/172035/como-criar-uma-virtualenv-com-uma-ves%C3%A3o-do-python-diferente-das-instaladas)
