### ISSUE TITLE
Utilizando tua source para um BOT Pago

### ISSUE THREAD

**Issue by manuloku** [Nucito/CaptchaSolver#6]
Primeiramente, perdoe criar uma ISSUE para algo que não é um ERRO,

Existe um Discord que está utilizando seu código, assim como o código do mpcabete para vender BOTs, por ser open-source acho inadequado o mesmo fazer isto. Porém caso ele tenha seu consentimento, retiro o que disse. Apenas reportando.

**Comment by Nucito** [comment]
@manuloku Teria o link ai?

**Comment by manuloku** [comment]
Tenho sim! https://discord.gg/B9U8eWZj

**Comment by Nucito** [comment]
> @Nucito Tenho sim! https://discord.gg/B9U8eWZj
> 
> Inclusive dentro do Download deles, tem o mesmo config.yaml do mpcabete... a única coisa que ele se deu o trabalho foi de proteger o código que nem é dele. Parece que ele retirou também o código de HOUSE, pra vender um bot mais caro com esta função. Fiquem de olho.

Ta safe kskssks ate agora eles foram o pessoal que fizeram mais donate kkkkkkk

**Comment by Nucito** [comment]
Mesmo assim, obrigado por me avisar😁
