### ISSUE TITLE
Erros em linhas

### ISSUE THREAD

**Issue by andrguima** [Nucito/CaptchaSolver#7]
Salve Salve, esta dando erros em linhas aqui

File "C:\bomb\index.py", line 4, in <module>
    from captcha.solveCaptcha import solveCaptcha
  File "C:\bomb\captcha\solveCaptcha.py", line 4, in <module>
    import mss
ModuleNotFoundError: No module named 'mss'

**Comment by Nucito** [comment]
@andrguima Era so ter seguido oq listei no readme...
pip install -r requirements.txt

**Comment by andrguima** [comment]
agora esta dando este, fiz todo o procedimento novamente

Traceback (most recent call last):
  File "C:\bomb\index.py", line 4, in <module>
    from captcha.solveCaptcha import solveCaptcha
  File "C:\bomb\captcha\solveCaptcha.py", line 13, in <module>
    model = torch.hub.load('./captcha', 'custom', "captcha/bomb_captcha.pt", source='local')
AttributeError: module 'torch' has no attribute 'hub'

**Comment by Nucito** [comment]
Isso ai não é do meu projeto... esse issue deveria ser feito no bot que vc esta usando😁
